### ISSUE TITLE
Can not find folder named [meshes] in ../data/meshes

### ISSUE THREAD

**Issue by FuXiii** [Raikiri/LegitEngine#4]
When execute `LegitEngine.exe` the `WaterRenderer` sample just fine, but when click the `PointRnderer` ,`SSVGIRenderer` and `VolumeRender` , log `can not find mesh file in ../data/meshes`
![image](https://user-images.githubusercontent.com/40132375/186062567-6997c508-1a63-4d1f-b4c6-a44a0b1b530d.png)

**Comment by Raikiri** [comment]
Thanks, I'll have to figure it out. Unfortunately, I don't have any credits saved for some of these models, so licensing can become an issue.

**Comment by Raikiri** [comment]
This should be fixed in https://github.com/Raikiri/LegitEngine/commit/68eb8083edfe19d324ccfd43d7a7ab2459894032
Let me know if there's anything else I need to do here to resolve the issue.

**Comment by FuXiii** [comment]
Ok! Everything is going well, thank you very much ,I will enjoy this amazing project.
If you have spare time , Can you create a sample about how to render a triangle? Your help would be greatly appreciated~
And thanks you shared this project.

**Comment by Raikiri** [comment]
There's a minimal code example on the main page of the project (in readme.md) that renders 4 vertices. Vertex coordinates can be assigned in a shader using gl_VertexIndex.

I thought of including that minimal example into the sources but I'm not sure how to organize the repo to contain all demos as well as the minimal example, so I just left it in the readme.

**Comment by FuXiii** [comment]
Ok, by the way can not found `DummyScene.json` file in `../data/scenes` Folder

**Comment by Raikiri** [comment]
All right I added the dummy scene.

**Comment by FuXiii** [comment]
Thanks

**Comment by Raikiri** [comment]
Can you resolve the issue if you think it's done?

**Comment by FuXiii** [comment]
Yes this issue had already resolved.

**Comment by Raikiri** [comment]
There's a "close issue" next to your "comment". It's usually a good practice for the person who opens an issue to close it themselves to indicate that their original problem is fixed.

**Comment by FuXiii** [comment]
Oh, Sorry I don't know it before, thank you kick me.
